name: "Slack Notify"
description: "Send a Slack notification for a GitHub Actions job"

runs:
  using: "composite"
  steps:
    - name: Notify Slack
      shell: bash
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_CHANNEL: ${{ inputs.slack-channel }}
        JOB_STATUS: ${{ inputs.job-status }}
        REPO_NAME: ${{ inputs.repo-name }}
        REF_NAME: ${{ inputs.ref-name }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        ACTOR: ${{ inputs.actor }}
        PR_NUMBER: ${{ inputs.pr-number }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
      run: |
        # Pick correct branch name
        if [ -n "$PR_NUMBER" ] && [ -n "$GITHUB_HEAD_REF" ]; then
          EFFECTIVE_REF="$GITHUB_HEAD_REF"
        else
          EFFECTIVE_REF="$REF_NAME"
        fi

        # Colors & emojis
        if [ "$JOB_STATUS" = "success" ]; then
          COLOR="#36a64f"
          EMOJI="✅"
        elif [ "$JOB_STATUS" = "cancelled" ]; then
          COLOR="#ffcc00"
          EMOJI="⚠️"
        else
          COLOR="#ff0000"
          EMOJI="❌"
        fi

        # Message text
        if [ -n "$PR_NUMBER" ]; then
          TEXT="$EMOJI Build \`$COMMIT_SHA\` of \`$REPO_NAME@$EFFECTIVE_REF\` in PR #$PR_NUMBER by $ACTOR $JOB_STATUS"
        else
          TEXT="$EMOJI Build \`$COMMIT_SHA\` of \`$REPO_NAME@$EFFECTIVE_REF\` by $ACTOR $JOB_STATUS"
        fi

        # Slack request
        curl -X POST \
          -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
          -H "Content-type: application/json" \
          --data "{
            \"channel\": \"$SLACK_CHANNEL\",
            \"attachments\": [
              {
                \"color\": \"$COLOR\",
                \"title\": \"Build Notification\",
                \"text\": \"$TEXT\",
                \"footer\": \"GitHub Actions\"
              }
            ]
          }" \
        https://slack.com/api/chat.postMessage

inputs:
  slack-bot-token:
    description: "Slack bot token"
    required: true
  slack-channel:
    description: "Slack channel ID"
    required: true
  job-status:
    description: "Job status (success, failure, cancelled)"
    required: true
  repo-name:
    description: "Repository name"
    required: true
  ref-name:
    description: "Branch or tag name"
    required: true
  commit-sha:
    description: "Commit SHA"
    required: true
  actor:
    description: "Actor who triggered the workflow"
    required: true
  pr-number:
    description: "Pull request number (optional)"
    required: false
